modLoader="javafml"
loaderVersion = "[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "[1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "gtolib"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ad_astra"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "deeperdarker"
mandatory = false
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"