modLoader="javafml"
loaderVersion = "[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "[1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ad_astra"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "deeperdarker"
mandatory = false
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ftbteams"
mandatory = true
versionRange = "[2001.3.2,2001.3.3)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "xaeroworldmap"
mandatory = true
versionRange = "[1.40.16,1.40.17)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "xaerominimap"
mandatory = true
versionRange = "[25.3.13,25.3.14)"
ordering = "AFTER"
side = "CLIENT"
